name: 代码质量检查

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black mypy bandit safety

    - name: Run Black (代码格式检查)
      run: |
        cd backend
        black app/ --check --verbose

    - name: Run Flake8 (代码风格检查)
      run: |
        cd backend
        flake8 app/ --statistics

    - name: Run MyPy (类型检查)
      run: |
        cd backend
        mypy app/ --ignore-missing-imports

    - name: Run Bandit (安全检查)
      run: |
        cd backend
        bandit -r app/ -f json -o bandit-report.json

    - name: Run Safety (依赖安全检查)
      run: |
        cd backend
        safety check --json --output safety-report.json

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Node.js dependencies
      run: |
        cd frontend
        npm ci

    - name: Run ESLint (JavaScript/TypeScript 检查)
      run: |
        cd frontend
        npm run lint

    - name: Run Prettier (代码格式检查)
      run: |
        cd frontend
        npm run format:check

    - name: Upload code quality reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: code-quality-reports
        path: |
          backend/bandit-report.json
          backend/safety-report.json